"""Domain models for Optima.

Mirrors the Class Diagram from the planning document: User, Subject,
Assignment, Constraint, ScheduleBlock. Designed so each object can round-trip
through JSON via .to_dict() / .from_dict() without losing precision.

All times on Constraint / ScheduleBlock are stored as decimal hours (9.5 =
9:30am) — that is the single backend representation. The user interface
formats them as 12h or 24h clock text depending on Preferences.time_format,
but the stored data never changes shape.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import date, datetime, timedelta
from typing import List, Optional


# Recognised values for Constraint.recurrence — these dictate how a single
# stored Constraint expands into many occurrences in the weekly/monthly view.
RECURRENCES = ("none", "daily", "weekly", "fortnightly", "monthly", "yearly")

# Recognised values for Constraint.kind — drives the icon/label and lets
# users filter by category. "subject" remains the default so seeded data
# (classes, study periods) keeps its meaning.
EVENT_KINDS = ("subject", "extracurricular", "appointment", "study", "other")


@dataclass
class Subject:
    id: int
    name: str
    colour: str = "#7B68EE"

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Subject":
        return cls(id=int(d["id"]), name=d["name"], colour=d.get("colour", "#7B68EE"))


@dataclass
class Constraint:
    """A fixed event such as a class period, appointment, or extracurricular.

    The first occurrence falls on ``anchor_date``; subsequent occurrences are
    generated by ``recurrence``. ``skip_dates`` removes specific instances
    (used by the "delete this instance" path on a repeating event) and
    ``override_dates`` carries per-instance edits — see ``InstanceOverride``.

    The legacy ``day_of_fortnight`` field is retained so existing user files
    keep working; on load it is converted into an ``anchor_date`` + fortnightly
    recurrence so older constraints continue to behave the same way.
    """

    id: int                       # stable id used by the JS editor
    name: str
    subject_id: Optional[int]
    start_time: float             # decimal hours, e.g. 9.25 for 9:15am
    end_time: float

    anchor_date: str = ""         # ISO yyyy-mm-dd — first occurrence
    recurrence: str = "weekly"    # see RECURRENCES
    kind: str = "subject"         # see EVENT_KINDS

    # Per-instance skips: ISO dates on which this constraint does NOT occur,
    # used by "delete only this instance" on a repeating event.
    skip_dates: List[str] = field(default_factory=list)
    # Per-instance edits — keyed by the ORIGINAL ISO date. Each entry is a
    # subset of {start_time, end_time, name} that overrides the stored values
    # on that one day only.
    overrides: dict = field(default_factory=dict)

    day_of_fortnight: int = 0     # legacy; only meaningful for recurrence == "fortnightly"
    is_half_period: bool = False
    is_study_period: bool = False

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Constraint":
        # Back-compat: very old files only stored day_of_fortnight. If no
        # anchor_date is present, fall back to fortnightly behaviour driven
        # by that integer index — main.py rebuilds an anchor at load time
        # when the user's term_start is known.
        recurrence = d.get("recurrence", "fortnightly" if "anchor_date" not in d else "weekly")
        if recurrence not in RECURRENCES:
            recurrence = "weekly"
        kind = d.get("kind", "subject")
        if kind not in EVENT_KINDS:
            kind = "subject"
        return cls(
            id=int(d.get("id", 0)),
            name=d["name"],
            subject_id=d.get("subject_id"),
            start_time=float(d["start_time"]),
            end_time=float(d["end_time"]),
            anchor_date=d.get("anchor_date", ""),
            recurrence=recurrence,
            kind=kind,
            skip_dates=list(d.get("skip_dates", [])),
            overrides=dict(d.get("overrides", {})),
            day_of_fortnight=int(d.get("day_of_fortnight", 0)),
            is_half_period=bool(d.get("is_half_period", False)),
            is_study_period=bool(d.get("is_study_period", False)),
        )

    # --------- occurrence model ------------------------------------------

    def occurs_on(self, target: date) -> bool:
        """Whether this constraint has an occurrence on ``target``.

        Honours skip_dates and the recurrence pattern. Always False before
        the anchor date.
        """
        if not self.anchor_date:
            return False
        if target.isoformat() in self.skip_dates:
            return False
        try:
            anchor = datetime.strptime(self.anchor_date, "%Y-%m-%d").date()
        except ValueError:
            return False
        if target < anchor:
            return False
        delta = (target - anchor).days
        if self.recurrence == "none":
            return delta == 0
        if self.recurrence == "daily":
            return True
        if self.recurrence == "weekly":
            return delta % 7 == 0
        if self.recurrence == "fortnightly":
            return delta % 14 == 0
        if self.recurrence == "monthly":
            return target.day == anchor.day
        if self.recurrence == "yearly":
            return target.day == anchor.day and target.month == anchor.month
        return False

    def occurrence_view(self, target: date) -> dict:
        """The instance-specific view of this constraint on ``target``.

        Applies any per-day overrides on top of the stored fields so callers
        get the values that should actually render for that day.
        """
        iso = target.isoformat()
        ov = self.overrides.get(iso, {}) if isinstance(self.overrides, dict) else {}
        return {
            "id": self.id,
            "date": iso,
            "name": ov.get("name", self.name),
            "start_time": float(ov.get("start_time", self.start_time)),
            "end_time": float(ov.get("end_time", self.end_time)),
            "subject_id": self.subject_id,
            "kind": self.kind,
            "recurrence": self.recurrence,
            "is_study_period": self.is_study_period,
            "is_half_period": self.is_half_period,
        }


@dataclass
class Assignment:
    id: int
    subject_id: int
    name: str
    due_date: str          # ISO yyyy-mm-dd
    weighting: float       # 0..100
    hours_required: float
    est_hours: float = 0.0
    completion_percent: float = 0.0
    completed: bool = False
    priority_score: float = 0.0
    # Encrypted private notes — base64 token produced by app.crypto.encrypt.
    # Stays opaque inside the on-disk JSON; only decryptable while the user
    # is logged in (their derived key sits in the Flask session).
    private_notes_encrypted: str = ""

    def days_remaining(self, today: Optional[date] = None) -> int:
        today = today or date.today()
        due = datetime.strptime(self.due_date, "%Y-%m-%d").date()
        return (due - today).days

    def remaining_hours(self) -> float:
        return max(0.0, self.hours_required * (1.0 - self.completion_percent))

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Assignment":
        return cls(
            id=int(d["id"]),
            subject_id=int(d["subject_id"]),
            name=d["name"],
            due_date=d["due_date"],
            weighting=float(d["weighting"]),
            hours_required=float(d["hours_required"]),
            est_hours=float(d.get("est_hours", 0.0)),
            completion_percent=float(d.get("completion_percent", 0.0)),
            completed=bool(d.get("completed", False)),
            priority_score=float(d.get("priority_score", 0.0)),
            private_notes_encrypted=d.get("private_notes_encrypted", ""),
        )


@dataclass
class ScheduleBlock:
    """A block of time allocated for study on a particular assignment."""

    assignment_id: int
    date_iso: str          # yyyy-mm-dd
    start_time: float
    duration: float        # hours
    completed: bool = False

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "ScheduleBlock":
        return cls(
            assignment_id=int(d["assignment_id"]),
            date_iso=d["date_iso"],
            start_time=float(d["start_time"]),
            duration=float(d["duration"]),
            completed=bool(d.get("completed", False)),
        )


@dataclass
class Preferences:
    theme: str = "light"               # 'light' | 'dark'
    notifications: bool = True
    auto_save: bool = True
    high_contrast: bool = False
    focus_highlights: bool = True
    zoom: int = 100                    # percent
    time_format: str = "24h"           # '12h' | '24h' — UI-only; storage is always decimal hours

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Preferences":
        p = cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
        if p.time_format not in ("12h", "24h"):
            p.time_format = "24h"
        return p


@dataclass
class User:
    username: str
    password_hash: str
    salt: str
    study_points: int = 0
    wake_time: float = 6.5
    bed_time: float = 22.5
    term_start: str = ""              # ISO date when Week A starts
    subjects: List[Subject] = field(default_factory=list)
    constraints: List[Constraint] = field(default_factory=list)
    assignments: List[Assignment] = field(default_factory=list)
    schedule_blocks: List[ScheduleBlock] = field(default_factory=list)
    preferences: Preferences = field(default_factory=Preferences)

    def to_dict(self) -> dict:
        return {
            "username": self.username,
            "password_hash": self.password_hash,
            "salt": self.salt,
            "study_points": self.study_points,
            "wake_time": self.wake_time,
            "bed_time": self.bed_time,
            "term_start": self.term_start,
            "subjects": [s.to_dict() for s in self.subjects],
            "constraints": [c.to_dict() for c in self.constraints],
            "assignments": [a.to_dict() for a in self.assignments],
            "schedule_blocks": [b.to_dict() for b in self.schedule_blocks],
            "preferences": self.preferences.to_dict(),
        }

    @classmethod
    def from_dict(cls, d: dict) -> "User":
        return cls(
            username=d["username"],
            password_hash=d["password_hash"],
            salt=d["salt"],
            study_points=int(d.get("study_points", 0)),
            wake_time=float(d.get("wake_time", 6.5)),
            bed_time=float(d.get("bed_time", 22.5)),
            term_start=d.get("term_start", ""),
            subjects=[Subject.from_dict(x) for x in d.get("subjects", [])],
            constraints=[Constraint.from_dict(x) for x in d.get("constraints", [])],
            assignments=[Assignment.from_dict(x) for x in d.get("assignments", [])],
            schedule_blocks=[ScheduleBlock.from_dict(x) for x in d.get("schedule_blocks", [])],
            preferences=Preferences.from_dict(d.get("preferences", {})),
        )

    def next_subject_id(self) -> int:
        return max((s.id for s in self.subjects), default=0) + 1

    def next_assignment_id(self) -> int:
        return max((a.id for a in self.assignments), default=0) + 1

    def next_constraint_id(self) -> int:
        return max((c.id for c in self.constraints), default=0) + 1

    def subject_by_id(self, sid: int) -> Optional[Subject]:
        for s in self.subjects:
            if s.id == sid:
                return s
        return None

    def constraint_by_id(self, cid: int) -> Optional[Constraint]:
        for c in self.constraints:
            if c.id == cid:
                return c
        return None

    def migrate_constraints(self) -> bool:
        """Heal legacy data shapes after a User has been deserialised.

        Older user files stored constraints with only ``day_of_fortnight`` and
        no id or anchor_date. Once we know the user's term_start we can
        synthesise a sensible anchor (the first calendar date on which that
        day-of-fortnight index falls on/after term_start) and assign stable
        ids so the new editor can target them.

        Returns True if anything was changed (the caller can save in that
        case).
        """
        changed = False
        used_ids = {c.id for c in self.constraints if c.id}
        next_id = max(used_ids, default=0) + 1
        try:
            term_start = datetime.strptime(self.term_start, "%Y-%m-%d").date() if self.term_start else None
        except ValueError:
            term_start = None
        for c in self.constraints:
            if not c.id:
                c.id = next_id
                next_id += 1
                changed = True
            if not c.anchor_date and term_start is not None:
                # Walk forward from term_start until day-of-fortnight matches.
                target = term_start + timedelta(days=c.day_of_fortnight)
                c.anchor_date = target.isoformat()
                changed = True
            if c.recurrence not in RECURRENCES:
                c.recurrence = "weekly"
                changed = True
            if c.kind not in EVENT_KINDS:
                c.kind = "study" if c.is_study_period else "subject"
                changed = True
        return changed
