"""Domain models for Optima.

Mirrors the Class Diagram from the planning document: User, Subject,
Assignment, Constraint, ScheduleBlock. Designed so each object can round-trip
through JSON via .to_dict() / .from_dict() without losing precision.

All times on Constraint / ScheduleBlock are stored as decimal hours (9.5 =
9:30am) — that is the single backend representation. The user interface
formats them as 12h or 24h clock text depending on Preferences.time_format,
but the stored data never changes shape.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import date, datetime, timedelta
from typing import List, Optional


# Recognised values for Constraint.recurrence — these dictate how a single
# stored Constraint expands into many occurrences in the weekly/monthly view.
# "weekdays" = every Mon-Fri (school-week pattern); useful for classes that
# happen daily on weekdays but not weekends.
RECURRENCES = ("none", "daily", "weekdays", "weekly", "fortnightly", "monthly", "yearly")

# Recognised values for Constraint.kind — drives the icon/label and what the
# scheduler is allowed to do with the time. "study_block" is the *only* kind
# the auto-scheduler will use as a designated study zone (round-4 feedback);
# everything else is a hard blocker.
EVENT_KINDS = ("subject", "extracurricular", "study_block", "other")

# Recognised values for Assignment.type — only "exam" surfaces the weighting %
# input on the task form. Everything else is scored from importance.
TASK_TYPES = ("homework", "exam", "project")

# Recognised values for Assignment.importance — applied when type != exam.
TASK_IMPORTANCE = ("low", "medium", "high")

# Numeric weighting equivalents used by the priority calculator when a task
# has no explicit weighting % (i.e. type is homework or project). Tuned so
# importance=high is comparable to a heavy exam, importance=low is comparable
# to a quiz-sized assessment.
IMPORTANCE_WEIGHTING = {"low": 10.0, "medium": 25.0, "high": 50.0}


@dataclass
class Subject:
    id: int
    name: str
    colour: str = "#7B68EE"

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Subject":
        return cls(id=int(d["id"]), name=d["name"], colour=d.get("colour", "#7B68EE"))


@dataclass
class Constraint:
    """A fixed event such as a class period, appointment, or extracurricular.

    The first occurrence falls on ``anchor_date``; subsequent occurrences are
    generated by ``recurrence``. ``skip_dates`` removes specific instances
    (used by the "delete this instance" path on a repeating event) and
    ``override_dates`` carries per-instance edits — see ``InstanceOverride``.

    The legacy ``day_of_fortnight`` field is retained so existing user files
    keep working; on load it is converted into an ``anchor_date`` + fortnightly
    recurrence so older constraints continue to behave the same way.
    """

    id: int                       # stable id used by the JS editor
    name: str
    subject_id: Optional[int]
    start_time: float             # decimal hours, e.g. 9.25 for 9:15am
    end_time: float

    anchor_date: str = ""         # ISO yyyy-mm-dd — first occurrence
    recurrence: str = "weekly"    # see RECURRENCES
    kind: str = "subject"         # see EVENT_KINDS

    # Per-instance skips: ISO dates on which this constraint does NOT occur,
    # used by "delete only this instance" on a repeating event.
    skip_dates: List[str] = field(default_factory=list)
    # Per-instance edits — keyed by the ORIGINAL ISO date. Each entry is a
    # subset of {start_time, end_time, name} that overrides the stored values
    # on that one day only.
    overrides: dict = field(default_factory=dict)

    day_of_fortnight: int = 0     # legacy; only meaningful for recurrence == "fortnightly"
    is_half_period: bool = False
    is_study_period: bool = False

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Constraint":
        # Back-compat: very old files only stored day_of_fortnight. If no
        # anchor_date is present, fall back to fortnightly behaviour driven
        # by that integer index — main.py rebuilds an anchor at load time
        # when the user's term_start is known.
        recurrence = d.get("recurrence", "fortnightly" if "anchor_date" not in d else "weekly")
        if recurrence not in RECURRENCES:
            recurrence = "weekly"
        kind = d.get("kind", "subject")
        if kind not in EVENT_KINDS:
            kind = "subject"
        return cls(
            id=int(d.get("id", 0)),
            name=d["name"],
            subject_id=d.get("subject_id"),
            start_time=float(d["start_time"]),
            end_time=float(d["end_time"]),
            anchor_date=d.get("anchor_date", ""),
            recurrence=recurrence,
            kind=kind,
            skip_dates=list(d.get("skip_dates", [])),
            overrides=dict(d.get("overrides", {})),
            day_of_fortnight=int(d.get("day_of_fortnight", 0)),
            is_half_period=bool(d.get("is_half_period", False)),
            is_study_period=bool(d.get("is_study_period", False)),
        )

    # --------- occurrence model ------------------------------------------

    def occurs_on(self, target: date) -> bool:
        """Whether this constraint has an occurrence on ``target``.

        Honours skip_dates and the recurrence pattern. Always False before
        the anchor date.
        """
        if not self.anchor_date:
            return False
        if target.isoformat() in self.skip_dates:
            return False
        try:
            anchor = datetime.strptime(self.anchor_date, "%Y-%m-%d").date()
        except ValueError:
            return False
        if target < anchor:
            return False
        delta = (target - anchor).days
        if self.recurrence == "none":
            return delta == 0
        if self.recurrence == "daily":
            return True
        if self.recurrence == "weekdays":
            # Mon-Fri only. weekday() returns 0..6 (Mon..Sun).
            return target.weekday() < 5
        if self.recurrence == "weekly":
            return delta % 7 == 0
        if self.recurrence == "fortnightly":
            return delta % 14 == 0
        if self.recurrence == "monthly":
            return target.day == anchor.day
        if self.recurrence == "yearly":
            return target.day == anchor.day and target.month == anchor.month
        return False

    def occurrence_view(self, target: date) -> dict:
        """The instance-specific view of this constraint on ``target``.

        Applies any per-day overrides on top of the stored fields so callers
        get the values that should actually render for that day.
        """
        iso = target.isoformat()
        ov = self.overrides.get(iso, {}) if isinstance(self.overrides, dict) else {}
        return {
            "id": self.id,
            "date": iso,
            "name": ov.get("name", self.name),
            "start_time": float(ov.get("start_time", self.start_time)),
            "end_time": float(ov.get("end_time", self.end_time)),
            "subject_id": self.subject_id,
            "kind": self.kind,
            "recurrence": self.recurrence,
            "is_study_period": self.is_study_period,
            "is_half_period": self.is_half_period,
        }


DEFAULT_DUE_TIME = 9.0   # 09:00 when the user leaves the time field blank


@dataclass
class Assignment:
    id: int
    subject_id: int
    name: str
    due_date: str          # ISO yyyy-mm-dd
    hours_required: float
    weighting: float = 0.0  # 0..100, only meaningful for type == "exam"
    type: str = "homework"  # see TASK_TYPES
    importance: str = "medium"  # see TASK_IMPORTANCE (applied when type != exam)
    show_stretch_line: bool = True   # render a coloured bar across the monthly view
    # Time of day the task is due, decimal hours. 09:00 by default — the
    # client picked it as "start of school day". Combined with due_date this
    # gives the precise due_at datetime the scheduler / priority calc use.
    due_time: float = DEFAULT_DUE_TIME
    est_hours: float = 0.0
    completion_percent: float = 0.0
    completed: bool = False
    priority_score: float = 0.0
    # Encrypted private notes — base64 token produced by app.crypto.encrypt.
    # Stays opaque inside the on-disk JSON; only decryptable while the user
    # is logged in (their derived key sits in the Flask session).
    private_notes_encrypted: str = ""

    def days_remaining(self, today: Optional[date] = None) -> int:
        today = today or date.today()
        due = datetime.strptime(self.due_date, "%Y-%m-%d").date()
        return (due - today).days

    def due_at(self) -> datetime:
        """Combine due_date + due_time into a single naive datetime.

        Naive (no tzinfo) because the whole app runs in the user's local
        clock and we never persist a tz; comparing against
        ``datetime.now()`` does the right thing.
        """
        d = datetime.strptime(self.due_date, "%Y-%m-%d")
        h = int(self.due_time)
        m = int(round((self.due_time - h) * 60))
        if m == 60:
            h += 1
            m = 0
        # Clamp the hour to 0..23 — the form already validates this but we
        # don't want a corrupt save to crash everyone.
        h = max(0, min(23, h))
        return d.replace(hour=h, minute=m)

    def hours_until_due(self, now: Optional[datetime] = None) -> float:
        """Signed hours until the due datetime — negative when overdue."""
        now = now or datetime.now()
        return (self.due_at() - now).total_seconds() / 3600.0

    def is_overdue(self, now: Optional[datetime] = None) -> bool:
        if self.completed:
            return False
        return self.hours_until_due(now) < 0

    def remaining_hours(self) -> float:
        return max(0.0, self.hours_required * (1.0 - self.completion_percent))

    def scoring_weight(self) -> float:
        """The numeric weight fed into the priority formula.

        For exams we use the user-entered weighting %. For homework/project
        we read off the importance map so a 'high' homework competes with a
        mid-sized exam, a 'low' homework competes with a quiz, etc.
        """
        if self.type == "exam":
            return float(self.weighting)
        return IMPORTANCE_WEIGHTING.get(self.importance, IMPORTANCE_WEIGHTING["medium"])

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Assignment":
        t = d.get("type", "homework")
        if t not in TASK_TYPES:
            t = "homework"
        imp = d.get("importance", "medium")
        if imp not in TASK_IMPORTANCE:
            imp = "medium"
        return cls(
            id=int(d["id"]),
            subject_id=int(d["subject_id"]),
            name=d["name"],
            due_date=d["due_date"],
            weighting=float(d.get("weighting", 0.0)),
            hours_required=float(d["hours_required"]),
            type=t,
            importance=imp,
            show_stretch_line=bool(d.get("show_stretch_line", True)),
            due_time=float(d.get("due_time", DEFAULT_DUE_TIME)),
            est_hours=float(d.get("est_hours", 0.0)),
            completion_percent=float(d.get("completion_percent", 0.0)),
            completed=bool(d.get("completed", False)),
            priority_score=float(d.get("priority_score", 0.0)),
            private_notes_encrypted=d.get("private_notes_encrypted", ""),
        )


@dataclass
class ScheduleBlock:
    """A block of time allocated for study on a particular assignment.

    ``is_break`` distinguishes the small "rest" gaps the scheduler inserts
    between back-to-back study sessions inside a single designated zone.
    Breaks are rendered implicitly on the weekly grid (i.e. as empty space)
    but the day-hover tooltip lists them so the user can see *when* the
    rest is and how long.
    """

    assignment_id: int
    date_iso: str          # yyyy-mm-dd
    start_time: float
    duration: float        # hours
    completed: bool = False
    is_break: bool = False

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "ScheduleBlock":
        return cls(
            assignment_id=int(d["assignment_id"]),
            date_iso=d["date_iso"],
            start_time=float(d["start_time"]),
            duration=float(d["duration"]),
            completed=bool(d.get("completed", False)),
            is_break=bool(d.get("is_break", False)),
        )


@dataclass
class Period:
    """A reusable time-of-day preset (Period 1, Period 2, ...) used to
    pre-fill the event editor so the user doesn't retype the same times.

    Pure user data — has no effect on scheduling. The weekly editor's
    "Use preset" dropdown lists these.
    """

    id: int
    name: str
    start_time: float    # decimal hours
    end_time: float

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Period":
        return cls(
            id=int(d["id"]),
            name=str(d["name"])[:60],
            start_time=float(d["start_time"]),
            end_time=float(d["end_time"]),
        )


@dataclass
class Preferences:
    theme: str = "light"               # 'light' | 'dark'
    notifications: bool = True
    auto_save: bool = True
    high_contrast: bool = False
    focus_highlights: bool = True
    zoom: int = 100                    # percent
    time_format: str = "24h"           # '12h' | '24h' — UI-only; storage is always decimal hours

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Preferences":
        p = cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
        if p.time_format not in ("12h", "24h"):
            p.time_format = "24h"
        return p


@dataclass
class User:
    username: str
    password_hash: str
    salt: str
    study_points: int = 0
    # Wake / bed are the *broad* awake window — used as the outer envelope
    # for the weekly grid render. Sleep is the explicit "do not schedule"
    # range (round-4 feedback: the scheduler kept placing study blocks at
    # 2 AM because the awake window was effectively the whole day).
    wake_time: float = 6.5
    bed_time: float = 23.0
    sleep_start: float = 22.5         # do-not-schedule starts here
    sleep_end: float = 6.5             # ... and ends here the next morning
    term_start: str = ""              # ISO date when Week A starts
    subjects: List[Subject] = field(default_factory=list)
    constraints: List[Constraint] = field(default_factory=list)
    assignments: List[Assignment] = field(default_factory=list)
    schedule_blocks: List[ScheduleBlock] = field(default_factory=list)
    periods: List[Period] = field(default_factory=list)
    preferences: Preferences = field(default_factory=Preferences)

    def to_dict(self) -> dict:
        return {
            "username": self.username,
            "password_hash": self.password_hash,
            "salt": self.salt,
            "study_points": self.study_points,
            "wake_time": self.wake_time,
            "bed_time": self.bed_time,
            "sleep_start": self.sleep_start,
            "sleep_end": self.sleep_end,
            "term_start": self.term_start,
            "subjects": [s.to_dict() for s in self.subjects],
            "constraints": [c.to_dict() for c in self.constraints],
            "assignments": [a.to_dict() for a in self.assignments],
            "schedule_blocks": [b.to_dict() for b in self.schedule_blocks],
            "periods": [p.to_dict() for p in self.periods],
            "preferences": self.preferences.to_dict(),
        }

    @classmethod
    def from_dict(cls, d: dict) -> "User":
        return cls(
            username=d["username"],
            password_hash=d["password_hash"],
            salt=d["salt"],
            study_points=int(d.get("study_points", 0)),
            wake_time=float(d.get("wake_time", 6.5)),
            bed_time=float(d.get("bed_time", 23.0)),
            sleep_start=float(d.get("sleep_start", 22.5)),
            sleep_end=float(d.get("sleep_end", 6.5)),
            term_start=d.get("term_start", ""),
            subjects=[Subject.from_dict(x) for x in d.get("subjects", [])],
            constraints=[Constraint.from_dict(x) for x in d.get("constraints", [])],
            assignments=[Assignment.from_dict(x) for x in d.get("assignments", [])],
            schedule_blocks=[ScheduleBlock.from_dict(x) for x in d.get("schedule_blocks", [])],
            periods=[Period.from_dict(x) for x in d.get("periods", [])],
            preferences=Preferences.from_dict(d.get("preferences", {})),
        )

    def next_subject_id(self) -> int:
        return max((s.id for s in self.subjects), default=0) + 1

    def next_assignment_id(self) -> int:
        return max((a.id for a in self.assignments), default=0) + 1

    def next_constraint_id(self) -> int:
        return max((c.id for c in self.constraints), default=0) + 1

    def next_period_id(self) -> int:
        return max((p.id for p in self.periods), default=0) + 1

    def subject_by_id(self, sid: int) -> Optional[Subject]:
        for s in self.subjects:
            if s.id == sid:
                return s
        return None

    def constraint_by_id(self, cid: int) -> Optional[Constraint]:
        for c in self.constraints:
            if c.id == cid:
                return c
        return None

    def period_by_id(self, pid: int) -> Optional[Period]:
        for p in self.periods:
            if p.id == pid:
                return p
        return None
